### PR TITLE
Allow prerelease DiagnosticSource package

### PR DESCRIPTION
**Pull request by lmolkova**
Fix dependency version for DiagnosticSource: there is no stable 4.4.0 version yet

### CODE REVIEW

**Comment by Dmitry-Matveev** [comment]
You may want to reference specific version of DiagnosticSource (pre-release) to make sure that changes in DiagnosticSource on its way to release won't fail SDK builds in case or the broken backcompat. Otherwise builds will always pick up the latest available pre-release and it may not be compatible or may break some scenarios unexpectedly.

**Comment by lmolkova** [comment]
I'm monitoring any changes in DiagnosticSource and it's also quite important to know that some changes there break compatibility with AppInsights, sooner we know about it the better 👍

**Comment by lmolkova** [comment]
@SergeyKanzhelev @Dmitry-Matveev 
Hey, could you please merge it? Without it it's not possible to install fresh AI nuget, because it depends on something that does not exist yet.

me and @karolz-ms are blocked on it

**Comment by SergeyKanzhelev** [comment]
I'll kick off the signed build in a sec

**Comment by lmolkova** [comment]
@SergeyKanzhelev  Thanks!

**Pull request merged**
