### PR TITLE
Make operation detail name constants public

### PR DESCRIPTION
**Pull request by OskarKlintrot**
Fix Issue #1326 . Also step nr 1 in issue #1350.

## Changes
Moved operation detail names from `RemoteDependencyConstants` to a new class and exposed as public.

### Checklist
- [ ] I ran Unit Tests locally.  <-- Having trouble building the solution and running the tests. At least it seems as if the tests that fail in my branch (on my computer) fails in main as well.
- [x] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #1326 
- [ ] Changes in public surface reviewed

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by OskarKlintrot** [comment]
@TimothyMothra Would you mind re-trigger the tests so I can see if I did it right with the public API, that's what failed last time. Also, is it possible to see the build logs somehow? I see that there are two jobs that has run and failed but I can't see the logs, they seem to be on Azure DevOps where they are not public. I can build my PR locally with `dotnet build` (it's the only way I can build it atm; #2178) so I can't really see what is going on.

**Comment by TimothyMothra** [comment]
Hi @OskarKlintrot, for your PR please use the text file named "Unshipped".
We use that for changes in beta versions. 

(This reminds me I forgot to move those contents to the "Shipped" file after our 2.20 release. I'll do that today.)

Regarding build logs, I would expect that you can view the github build logs.
This was one of the driving reasons to move our unit tests to github! 
Please let me know if you're unable to view them, maybe I overlooked one of the permissions and I definitely want to fix this.
As a workaround, you should be able to trigger these in your forked repo.

The one build running in Azure Pipelines is our compliance tools.
I can't make this one public, but I can share the logs if we get blocked on this.

**Comment by OskarKlintrot** [comment]
Oh, I didn't know I could run the builds on my fork, that's neat! It's still failing after I moved them to `unshipped` though:
```Error: D:\a\ApplicationInsights-dotnet\ApplicationInsights-dotnet\WEB\Src\DependencyCollector\DependencyCollector\OperationDetailConstants.cs(6,25): error RS0016: Symbol 'OperationDetailConstants' is not part of the declared API [D:\a\ApplicationInsights-dotnet\ApplicationInsights-dotnet\WEB\Src\DependencyCollector\DependencyCollector\DependencyCollector.csproj]```
Should I add something somewhere else? Or did I just use the wrong format?

I hope that if I fix this error the build on Azure should work as well.

**Comment by OskarKlintrot** [comment]
I think I missed adding the class itself to the public api, building again on my fork.

**Comment by OskarKlintrot** [comment]
Nope, still not working:
```
Error: D:\a\ApplicationInsights-dotnet\ApplicationInsights-dotnet\WEB\Src\DependencyCollector\DependencyCollector\OperationDetailConstants.cs(6,25): error RS0016: Symbol 'OperationDetailConstants' is not part of the declared API [D:\a\ApplicationInsights-dotnet\ApplicationInsights-dotnet\WEB\Src\DependencyCollector\DependencyCollector\DependencyCollector.csproj]
```
Not sure what I'm doing wrong?

**Comment by TimothyMothra** [comment]
The error message will be misleading, this Analyzer doesn't handle multi-framework projects well.
If you're using Visual Studio, it gives an option to fix this for you. Screenshots here: https://github.com/dotnet/roslyn-analyzers/issues/3322


The new api needs to be added to both frameworks in this directory (net452 and netstandard2.0)
https://github.com/microsoft/ApplicationInsights-dotnet/tree/main/.publicApi/Microsoft.AI.DependencyCollector.dll

**Comment by OskarKlintrot** [comment]
Oh, I found that file just after posting and added it there as well. I didn't think it would solve anything though since net452 didn't build either. Glad to be mistaken, now everything looks green and lovely!

**Review by TimothyMothra — APPROVED** [review]
LGTM

**Pull request merged**
