### PR TITLE
Cut Phone and Store support

### PR DESCRIPTION
**Pull request by abaranch**

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
We are using UWP for aspnet5, do we?

**Comment by abaranch** [comment]
We use PCL for aspnet5

**Comment by SergeyKanzhelev** [comment]
@upendras , did you plan to switch to UWP? For some reason I thought we need UWP for aspnet5

**Comment by upendras** [comment]
not sure, i have to check this for generations support.

**Pull request merged**
