### PR TITLE
WorkerService project to depend on Microsoft.Extensions.DI 2.1.1

### PR DESCRIPTION
**Pull request by cijothomas**
Fix Issue #1677  .

## Changes
(Please provide a brief description of the changes here.)

### Checklist
- [ ] I ran Unit Tests locally.
- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by pramadhav** [comment]
Thanks for working on this. I have a release at work that is breaking the builds which use .NET Core 2.1. Current DI version is 2.1.1. Any idea when the package would be ready and part of which version?

**Comment by cijothomas** [comment]
This will be part of next beta1, due to be released in 1-2 weeks.

**Comment by pramadhav** [comment]
Thank you for the update

**Comment by pramadhav** [comment]
> This will be part of next beta1, due to be released in 1-2 weeks.

Hi, Does 2.14 includes your fix on DI reference to 2.1.1? In the Nuget dependencies, DI dependency is still showing >2.2 for 2.14.0 version

**Comment by TimothyMothra** [comment]
Hello, @pramadhav 2.14 does not include this change.
2.14 had some issues that required our attention so the 2.15-beta1 was pushed back another week.

Is this a blocking issue for you? We can have a conversation about expediting the next beta if you'd be willing to validate this change.

**Comment by pramadhav** [comment]
> Hello, @pramadhav 2.14 does not include this change.
> 2.14 had some issues that required our attention so the 2.15-beta1 was pushed back another week.
> 
> Is this a blocking issue for you? We can have a conversation about expediting the next beta if you'd be willing to validate this change.

hi,  Yes, We are really waiting on this fix and anything that you could expedite would greatly help us.  I can test my side when the beta is available and update you. In terms of evidence, I cannot provide much as my project is proprietary and confidential to my employer.

**Comment by TimothyMothra** [comment]
Hi @pramadhav Sorry for the delay,
We just started the release process for the 2.15-Beta1. It should be available by Friday (5/01)

**Comment by TimothyMothra** [comment]
@pramadhav we just released 2.15-Beta1
It should be available on NuGet within the hour ;)
We would love to get your feedback on if this fixes your issue!

**Comment by pramadhav** [comment]
sure, will test out in update in the next couple of days

**Comment by pramadhav** [comment]
my initial test was successful with DI 2.1.1 dependency. Planning to do more comprehensive test with the Exceptions. Quick question meanwhile
I have wrapped ASPNETCore and WorkerService nuget packages in a C# .NET standard library and using it in our team's  .NET Core/ASP.NET core apps. My colleagues want to use it from Java apps too. I would like to explore this, can you please let me know the laetst Java SDK name for App Insights? I appreciate any guidance on that.

**Pull request merged**
