### PR TITLE
Changed telemetry channel to not retry on 402 response from API

### PR DESCRIPTION
**Pull request by madeleinefletcher**

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Is there retry on client side errors like DNS resolution? Do we retry on 502? 
CC: @upendras 
@lukekim , what other status codes should we expect from DC?

**Comment by madeleinefletcher** [comment]
As far as I can tell the only retries are on too many requests: 429 and 439.

**Comment by upendras** [comment]
We do retries for 500 class errors, but that is in a different error handing policy. The throttling policy only deals with 402,429 and 439 and the retry is guided by server hint in retry-after header.

**Comment by SergeyKanzhelev** [comment]
Ok, makes sense. :shipit:

**Pull request merged**
