### PR TITLE
[Prototype] Support ActivityLinks

### PR DESCRIPTION
**Pull request by pakrym**
Currently, Azure SDKs produce a special kind of Activities that carries links in a 
``` C#
public IEnumerable<Activity> Links { get; }
```
property.

Migration to ActivitySource based activities would result in the same information being carried in the 
https://docs.microsoft.com/en-us/dotnet/api/system.diagnostics.activity.links?view=net-5.0

This PR add support for collecting both ways of representing links.

### CODE REVIEW

**Comment by pakrym** [comment]
cc @lmolkova

**Review by lmolkova — APPROVED** [review]

**Comment by pakrym** [comment]
@rajkumar-rangaraj any news on this? The .NET 5 activity link support has shipped in Azure SDKs

**Pull request closed without merging**
