### PR TITLE
Testing builds, do not merge

### PR DESCRIPTION
**Pull request by TimothyMothra**

### CODE REVIEW

**Comment by heyams** [comment]
image

fix webhook then the linking should work.

**Comment by heyams** [comment]
nice.. just curious.. they remove it for you?

**Comment by TimothyMothra** [comment]
@heyams I opened a support ticket to Azure Pipelines in early December.
It took a lot of back-and-forth before they would acknowledge the issue.
They had to manually remove the connection on their end.

**Comment by TimothyMothra** [comment]
# IT WORKS!!!!

**Pull request closed without merging**
