### PR TITLE
[WIP] configuring source link

### PR DESCRIPTION
**Pull request by eddynaka**
Fix Issue #1760 .

See comment history on original PR: #1800

## Changes
- configuring source link based on https://github.com/dotnet/sourcelink

### Checklist
- [ ] I ran Unit Tests locally.
- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by TimothyMothra** [comment]
builds are passing but still not embedding sourcelink
image

**Comment by eddynaka** [comment]
I'm checking with some people whats happening. When i generate the nupkg locally, the xml from the dll/pdb has the sourcelink. But, when we move to ADO Pipeline, the same tag doesn't exist.

**Comment by TimothyMothra** [comment]
i wonder if this has something to do with your private fork. 
later this afternoon I can make a private branch in this repo and test your changes

**Comment by eddynaka** [comment]
closing this, since i opened one inside the application insights repository

**Pull request closed without merging**
