### PR TITLE
Replacing LicenseUrl property with license as it's deprecated

### PR DESCRIPTION
**Pull request by armanik11**
Fix Issue #1036
LicenseUrl is deprecated. This has been replaced with license property.

- [x] I ran Unit Tests locally.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed
- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue.
- [ ] The PR will trigger build, unit tests, and functional tests automatically. If your PR was submitted from fork - mention one of committers to initiate the build for you.
	  If you want to to re-run the build/tests, the easiest way is to simply Close and Re-Open this same PR. (Just click 'close pull request' followed by 'open pull request' buttons at the bottom of the PR)

- Please follow [these] (https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### CODE REVIEW

**Comment by MS-TimothyMothra** [comment]
Should we be using this in addition to your update?
`<PackageLicenseFile>License.txt</PackageLicenseFile>`

I like the simplicity of specifying just `MIT` like you've done here, but I also like the check list that github displays with the License page.

My nuget audit script might fail the build because this change removes the license url.
Microsoft's guidance seems to suggest that the license url is required, but this obviously conflicts with the depricated field. https://aka.ms/nuget​
**TODO:** I'm waiting to see the bulid result, but i'm expecting that may need to be updated.

TODO: We need to make sure that the Visual Studio accept license prompt is unaffected by this change.
Once the master build completes, we can manually the nupkg and verify.

**Comment by SergeyKanzhelev** [comment]
@MS-TimothyMothra packaging file explicitly only needed when your file is different from the original license. Specifying MIT is a recommended approach

**Comment by SergeyKanzhelev** [comment]
I'm sorry I merged before I saw your comment. Let me know if I need to revert

**Comment by MS-TimothyMothra** [comment]
I'm okay with that. I just didn't see that mentioned in the MS Guidelines

**Pull request merged**
