### PR TITLE
Fix PropertyFetcher error when used with multiple types

### PR DESCRIPTION
**Pull request by JamesNK**
Fix Issue #2194 .

## Changes
Update PropertyFetch to support getting property from multiple types. The change in this PR updates PropertyFetch to match what is in runtime - https://github.com/dotnet/corefx/blob/b8b81a66738bb10ef0790023598396861d92b2c4/src/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs#L854-L865

### Checklist
- [x] I ran Unit Tests locally.
- [x] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by JamesNK** [comment]
Is the fix in this PR ok? Is merging waiting on some event?

**Review by TimothyMothra — APPROVED** [review]

**Pull request merged**
