### PR TITLE
Add configurable SyntheticUserAgentTelemetryInitializer (#1963)

### PR DESCRIPTION
**Pull request by fabricebauer**
## Changes
Add equivalent of existing one in ASP.Net with default filters values and possibility
to configure (via IConfiguration injection) or customize filters (via setter).

### Checklist
- [x] I ran Unit Tests locally.
- [x] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Review by cijothomas — CHANGES_REQUESTED** [review]
Instead of adding a new initializer, we should just make the existing one customizable.

**Comment by fabricebauer** [comment]
> Instead of adding a new initializer, we should just make the existing one customizable.

I thought about it indeed, but the existing one seems very specific to "Application Insights Availability Monitoring", so I thought it might be better/more flexible to have a dedicated one for "User-agent" related values. 

Also the existing one is added by default in AddAspNetCoreWebTelemetryInitializers, not for the new one, as I thought not everybody might want it by default (there is a slight performance penalty checking filters values).
 
What do you think? 
I am ok with both approaches, so if you still think it is better to have a single one, I will do the changes and submit another PR.

Thanks.

**Comment by cijothomas** [comment]
>  but the existing one seems very specific to "Application Insights Availability Monitoring", so I thought it might be better/more flexible to have a dedicated one for "User-agent" related values.

This is not the case. There is nothing specific to ApplicationInsights Availability monitoring in that initializer.

**Comment by cijothomas** [comment]
> lso the existing one is added by default in AddAspNetCoreWebTelemetryInitializers, not for the new one, as I thought not everybody might want it by default (there is a slight performance penalty checking filters values).

We can do similar approach as whats done in asp.net. (https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/Web/Web/SyntheticUserAgentTelemetryInitializer.cs#L17)
Empty filters by default. So perf hit is only for those user's who add more filters to it.
(In case of asp.net, the default AI.config file has a bunch of filters - https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/WEB/Src/Web/Web/net452/ApplicationInsights.config.install.xdt#L8 . I think it'd be okay to have the same defaults for aspnetcore as well)

**Comment by fabricebauer** [comment]
Closing this PR, submitted new PR https://github.com/microsoft/ApplicationInsights-dotnet/pull/2148

**Pull request closed without merging**
