### PR TITLE
Initial sampling rate from applicationHost.config fix

### LINKED ISSUE #926: AdaptiveSamplingProcessor constructor doesn't respect arguments passed
If you are reporting bug/issue, please provide detailed Repro instructions.

## Repro Steps
When `SamplingPercentageEstimatorSettings` passed into `AdaptiveSamplingTelemetryProcessor` - it's settings are not used. See below for example.

##  Actual Behavior

This code will not apply 25 as an initial sampling percentage

```
var samplingProcessor = new AdaptiveSamplingTelemetryProcessor(
  new SamplingPercentageEstimatorSettings() {
      InitialSamplingPercentage = 25
  }, 
  null,
  next);
```

## Expected Behavior

Settings like `InitialSamplingPercentage`, `MinSamplingPercentage` and others should be applied on constructor.

## Workaround

Workaround is to set properties explicitly:

``` csharp
var samplingProcessor = new AdaptiveSamplingTelemetryProcessor(next);
samplingProcessor.InitialSamplingPercentage = 25;
```

## Version Info 
SDK Version :
.NET Version :	 						
How Application was onboarded with SDK(VisualStudio/StatusMonitor/Azure Extension) :
OS :
Hosting Info (IIS/Azure WebApps/ etc) :

### PR DESCRIPTION
**Pull request by Mikhail-Pranovich**
Fix of an InitialSamplingRate, when setting it through the applicationHost.config would not apply it.
Also resolves #926.

- [x] I ran [Unit Tests](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) locally.

For significant contributions please make sure you have completed the following items:

- [] Design discussion issue #
- [x] Changes in public surface reviewed
- [x] CHANGELOG.md updated with one line description of the fix, and a link to the original issue.
- [x] The PR will trigger build, unit test, and functional tests automatically. If your PR was submitted from fork - mention one of committers to initiate the build for you.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
Does it address https://github.com/Microsoft/ApplicationInsights-dotnet/issues/926 as well?

**Comment by Mikhail-Pranovich** [comment]
> Does it address #926 as well? If not - can you please include that fix as well.
@SergeyKanzhelev, I cannot repro the issue you mentioned using latest develop bits. Do you have more details on the issue?

**Comment by Mikhail-Pranovich** [comment]
> > Does it address #926 as well? If not - can you please include that fix as well.
> 
> @SergeyKanzhelev, I cannot repro the issue you mentioned using latest develop bits. Do you have more details on the repro steps?

The issue was that inner SamplingTelemetryProcessor did not have the SamplingPercentage set to initial value. This is now fixed. Note changing behavior of Min-Max vs InitialSamplingPercentage is out of scope of this PR.

**Comment by SergeyKanzhelev** [comment]
>Note changing behavior of Min-Max vs InitialSamplingPercentage is out of scope of this PR.

Can you please make a remark in issue I referred to explaining what is fixed and what is not. Or create a separate one

**Pull request merged**
