### PR TITLE
Cleaning AssemblyInfo.cs and *.csproj

### PR DESCRIPTION
**Pull request by eddynaka**
Fix Issue # .

## Changes
- removing extra tags in assemblyinfo.cs / *.csproj

### Checklist
- [ ] I ran Unit Tests locally.
- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by eddynaka** [comment]
Questions:
- in some **test** projects we have `AssemblyInfo.cs` and other we don't. Should we exclude all or add for all? Example: `DiagnosticSourceListener.Tests` doesn't have and `EtwCollector.Tests` have.
- `<IsPackable>` is used in almost all test projects. Since we don't use the `Product.props` file, it's not generating the package. Should we remove as well?

**Comment by TimothyMothra** [comment]
I think the `<IsPackable>false</IsPackable>` could be moved to the common Test.props file.

I'm not sure what to do with the AssemblyInfo.cs. I think it's not required for PackageReference csproj. We may need to make a case by case decision if they can be removed from the Test projects. 
Are they causing an issue or are you trying to cleanup inconsistencies?

**Comment by eddynaka** [comment]
> I think the `<IsPackable>false</IsPackable>` could be moved to the common Test.props file.
> 
> I'm not sure what to do with the AssemblyInfo.cs. I think it's not required for PackageReference csproj. We may need to make a case by case decision if they can be removed from the Test projects.
> Are they causing an issue or are you trying to cleanup inconsistencies?

Ok, i will add the IsPackable to test.props
For the AssemblyInfo, just cleaning the inconsistencies.

**Comment by TimothyMothra** [comment]
LGTM. Please click "Ready for review" when you're finished with these changes. :)

**Pull request merged**
