### PR TITLE
Listen to Microsoft.Data.Sqlclient 2.0+ events as well as those from …

### PR DESCRIPTION
**Pull request by ulf-cab**
…System.Data(.SqlClient).

Fix Issue #2032  .

## Changes
Se title.

### Checklist
- [ ] I ran Unit Tests locally.

No, the dependencies of Mds (net46) would require creating an entirely new test project for this and I am not comfortable enough with this codebase to do that.

Sidenote, why is there SqlClientDiagnosticSourceListenerTests.cs and SqlClientDiagnosticSourceListenerTestsCopy.cs?

- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

No, that would be a bit premature...

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by cjindustries** [comment]
Hi, what's the blocker on getting this PR in and issue #2032 fixed?

**Comment by ulf-cab** [comment]
I (as the author of the code in this PR) did not add any tests to actually validate that this fixes the issue. That would involve creating a new test project that is compatible with the requirements of MDS or upgrading the current project to Net Fwk 4.6. 

While I could figure out what was wrong and add a fix that compiles, doing the test thing would be going deeper into the rabbit hole than I can do right now.

So I left the PR as a draft (so non-merge:able) here hoping that would at least help someone else fix the issue faster.

**Comment by cijothomas** [comment]
Sorry for the delay - Will review this and include this in 2.17 release, as 2.16 is a light release with only major change is just the version bump of DiagnosticSource nuget version.

**Comment by cijothomas** [comment]
We should be able to merge this as-is. And as a follow up add actual tests for validation.

**Comment by ulf-cab** [comment]
OK, I have changed it from draft to Open/Ready for review.

**Review by TimothyMothra — APPROVED** [review]

**Pull request merged**
