### PR TITLE
Address outstanding doc comments for metrics

### PR DESCRIPTION
**Pull request by macrogreg**
Addressing outstanding doc comments for metrics.

### CODE REVIEW

**Comment by TimothyMothra** [comment]
Thank you

**Comment by macrogreg** [comment]
@TimothyMothra thanks for the earlier review. I have now completed all the docs. Please let me know if you would like to re-review the change. We should squash-merge is with the following heading:

> Metrics: Address outstanding doc comments for metric APIs.

Also, I am getting a build break that I think is due t an unrelated test:

Failed   PerformanceCounterTelemetryDeepCloneCopiesAllProperties
Error Message:
 Assert.IsTrue failed. 
Begin Differences (1 differences):
Types [String,String], Item Expected.Context.Properties.Key != Actual.Context.Properties.Key, Values (p1,CounterInstanceName)
End Differences (Maximum of 1 differences shown).
Stack Trace:
   at Microsoft.ApplicationInsights.DataContracts.PerformanceCounterTelemetryTest.PerformanceCounterTelemetryDeepCloneCopiesAllProperties() in /mnt/a/1/s/Test/Microsoft.ApplicationInsights.Test/Shared/DataContracts/**PerformanceCounterTelemetryTest.cs**:line 52

**Comment by TimothyMothra** [comment]
Thanks @macrogreg .
Yeah, we still have a few tests that fail intermittently. We've been trying to stomp these out but it's very frustrating. 
I'll keep an eye on this so we can get it merged today.

**Comment by TimothyMothra** [comment]
#817

**Pull request merged**
