### PR TITLE
Add new constructor to TraceListener that accepts TelemetryConfiguration

### PR DESCRIPTION
**Pull request by eddynaka**
Fix Issue #1476.

- [X] I ran Unit Tests locally.
- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed
- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue.

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by eddynaka** [comment]
@TimothyMothra @lmolkova , i was checking with @SergeyKanzhelev about the CLSCompliant and that won't be possible due to the references that we have in Microsoft.ApplicationInsights (System.Diagnostics.Activity, for example).

**Comment by lmolkova** [comment]
so perhaps it's not possible to finish this work item. Does anyone know why we need it?

It is possible to keep using `TelemteryConfiguration.Active` and add telemetry initializers to it. It will be picked up by `ApplicationInsightsTraceListener` implicitly here 

https://github.com/microsoft/ApplicationInsights-dotnet/blob/develop/LOGGING/src/TraceListener/ApplicationInsightsTraceListener.cs#L42

So can we close it assuming `TelemteryConfiguration.Active` is a reasonable workaround?

**Comment by TimothyMothra** [comment]
@lmolkova the workitem came from a separate external contributor's PR.
At the time we agreed that the item was important, but the person wasn't responding to requests to update the original PR so i converted it to an Issue. The original PR is linked.

If we no longer need this it can be closed. :)

**Comment by eddynaka** [comment]
should i close this PR and you guys close the issue?

let me know :)

**Comment by TimothyMothra** [comment]
I'm closing this as it is no longer necessary and a workaround is available.

**Pull request closed without merging**
