### PR TITLE
Pcl to net standard conversion

### PR DESCRIPTION
**Pull request by SergeyKanzhelev**
CC: @dnduffy @karolz-ms @cijothomas @pharring

This seems to be working fine. https://www.myget.org/F/applicationinsights/api/v2 Version `2.3.0-beta2-build27851`

@karolz-ms you can do the same in logging repo. Can you?

### CODE REVIEW

**Comment by karolz-ms** [comment]
@SergeyKanzhelev Most likely yes, I can, but project.json is/will soon be obsolete. I'd rather wait a couple of weeks till dev15 ships and use the new tooling.

**Comment by SergeyKanzhelev** [comment]
@karolz-ms project.json looks very tiny. So not much investments here... Using this approach will allow to support .NET Core `ILogger` and `EventSource` by //build

**Comment by karolz-ms** [comment]
@SergeyKanzhelev OK, sounds good. Will submit a PR for `EventSource` in the next couple of days

**Comment by pharring** [comment]
As Sergey noted in #434 and I verified, we can also remove the netstandard1.3 dependencies from Package.nuspec. That could be done here or in a follow-up PR,

**Comment by SergeyKanzhelev** [comment]
We'll wait for VS 2017 RTM to use new `.csproj` approach

**Pull request closed without merging**
