### PR TITLE
enable net452

### PR DESCRIPTION
**Pull request by eddynaka**
Fix Issue #1161.

## Changes
- for each csproj, if we use `net45` or `net451` i added `net452`
- for each .cs, if we use `#if net45` or `#if net451` I added `#if net452`

### Checklist
- [x] I ran Unit Tests locally.
- [ ] CHANGELOG.md updated with one line description of the fix, and a link to the original issue if available.

For significant contributions please make sure you have completed the following items:

- [ ] Design discussion issue #
- [ ] Changes in public surface reviewed

The PR will trigger build, unit tests, and functional tests automatically. Please follow [these](https://github.com/Microsoft/ApplicationInsights-dotnet/blob/develop/.github/CONTRIBUTING.md) instructions to build and test locally.

### Notes for authors:
- FxCop and other analyzers will fail the build. To see these errors yourself, compile localy using the Release configuration.

### Notes for reviewers:

- We support [comment build triggers](https://docs.microsoft.com/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#comment-triggers)
  - `/AzurePipelines run` will queue all builds
  - `/AzurePipelines run <pipeline-name>` will queue a specific build

### CODE REVIEW

**Comment by eddynaka** [comment]
Questions:
- Right now, I added a new targetFramework for the tests as well. Should we merge net45 and net452? So we will only test one framework?
- I saw some cases where we test a higher framework, for example `EtwCollector`. It was targetting only 451 and the tests just targeted 46.

**Comment by eddynaka** [comment]
Changes that i saw we can try in new PR's:
- clean AssemblyInfo.cs: i saw some assemblyInfos that still have some lines that are pointing to excluded/merged projects
- clean Properties in *.csproj: with the last merges, i think we can remove all tags like `<GenerateAssembly**>`

**Comment by cijothomas** [comment]
@TimothyMothra Do we need to add net452 ? Can we simply replace net45 with net452?

**Comment by TimothyMothra** [comment]
My goals are, 
- how do we migrate our product to supported versions of .NET?
- how do we support customers during this transition?

@cijothomas I would prefer we add support for net452 first before removing net45, Similar to how we migrated away from NetStandard 1.x. 
In theory, this gives customers a stable version they can use to upgrade their products.

**Pull request merged**
